### PR TITLE
Configure download of EAD XML for the collection

### LINKED ISSUE #127: Configure collection XML for download

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #127

### CODE REVIEW

**Comment by marlo-longley** [comment]
@jcoyne is a working Download button intended to be part of this PR, or just the YAML setup?

**Comment by marlo-longley** [comment]
I am seeing this button, with both links going to `example.com`

Screen Shot 2022-11-02 at 12 20 54

**Comment by jcoyne** [comment]
@marlo-longley the download button is part of arclight, it's all about the configuration.  Can you tell me what url you were on where it was showing the download for pdf and ead?

**Comment by marlo-longley** [comment]
@jcoyne my bad. It looks correct after all. Will merge this.
Screen Shot 2022-11-02 at 12 43 19

**Comment by jcoyne** [comment]
Ah! There was a bad merge here: https://github.com/projectblacklight/arclight/commit/b823b9f55391af47c7367edb13a08a7a2ce26c1e#diff-6f5f2e15cf9cd3682ff504c957f5fe616b6fd7522f4fd2355be2ea59dd24b1daL9

**Comment by marlo-longley** [comment]
@jcoyne hmm - I did a `bundle update` to update arclight and refreshed and got the single EAD download. Seem good?

**Comment by jcoyne** [comment]
No, I think we need this to fix it: https://github.com/projectblacklight/arclight/pull/1264

**Comment by jcoyne** [comment]
I've updated this with the version of arclight that has fixed the merge bug.

**Review by corylown — APPROVED** [review]

**Pull request merged**
